occupationsGroupArr2 = [
'Management Occupations'];

occupationsGroupArr = [
'Management Occupations',
'Business and Financial Operations Occupations',
'Computer and Mathematical Occupations',
'Architecture and Engineering Occupations',
'Life, Physical, and Social Science Occupations',
'Community and Social Service Occupations',
'Legal Occupations',
'Education, Training, and Library Occupations',
'Arts, Design, Entertainment, Sports, and Media Occupations',
'Healthcare Practitioners and Technical Occupations',
'Healthcare Support Occupations',
'Protective Service Occupations',
'Food Preparation and Serving Related Occupations',
'Building and Grounds Cleaning and Maintenance Occupations',
'Personal Care and Service Occupations',
'Sales and Related Occupations',
'Office and Administrative Support Occupations',
'Farming, Fishing, and Forestry Occupations',
'Construction and Extraction Occupations',
'Installation, Maintenance, and Repair Occupations',
'Production Occupations',
'Transportation and Material Moving Occupations'];

detailGroupArr2 = ['Chief executives',
'General and operations managers'];

detailGroupArr = ['Chief executives',
'General and operations managers',
'Legislators',
'Advertising and promotions managers',
'Marketing managers',
'Sales managers',
'Public relations and fundraising managers',
'Administrative services managers',
'Computer and information systems managers',
'Financial managers',
'Industrial production managers',
'Purchasing managers',
'Transportation, storage, and distribution managers',
'Compensation and benefits managers',
'Human resources managers',
'Training and development managers',
'Farmers, ranchers, and other agricultural managers',
'Construction managers',
'Education administrators, preschool and childcare center/program',
'Education administrators, elementary and secondary school',
'Education administrators, postsecondary',
'Education administrators, all other',
'Architectural and engineering managers',
'Food service managers',
'Funeral service managers',
'Gaming managers',
'Lodging managers',
'Medical and health services managers',
'Natural sciences managers',
'Postmasters and mail superintendents',
'Property, real estate, and community association managers',
'Social and community service managers',
'Emergency management directors',
'Managers, all other',
'Agents and business managers of artists, performers, and athletes',
'Buyers and purchasing agents, farm products',
'Wholesale and retail buyers, except farm products',
'Purchasing agents, except wholesale, retail, and farm products',
'Claims adjusters, examiners, and investigators',
'Insurance appraisers, auto damage',
'Compliance officers',
'Cost estimators',
'Human resources specialists',
'Labor relations specialists',
'Logisticians',
'Management analysts',
'Meeting, convention, and event planners',
'Fundraisers',
'Compensation, benefits, and job analysis specialists',
'Training and development specialists',
'Market research analysts and marketing specialists',
'Business operations specialists, all other',
'Accountants and auditors',
'Appraisers and assessors of real estate',
'Budget analysts',
'Credit analysts',
'Financial analysts',
'Personal financial advisors',
'Insurance underwriters',
'Financial examiners',
'Credit counselors',
'Loan officers',
'Tax examiners and collectors, and revenue agents',
'Tax preparers',
'Financial specialists, all other',
'Computer and information research scientists',
'Computer systems analysts',
'Information security analysts',
'Computer programmers',
'Software developers, applications',
'Software developers, systems software',
'Web developers',
'Database administrators',
'Network and computer systems administrators',
'Computer network architects',
'Computer user support specialists',
'Computer network support specialists',
'Computer occupations, all other',
'Actuaries',
'Mathematicians',
'Operations research analysts',
'Statisticians',
'Mathematical technicians',
'Mathematical science occupations, all other',
'Architects, except landscape and naval',
'Landscape architects',
'Cartographers and photogrammetrists',
'Surveyors',
'Aerospace engineers',
'Agricultural engineers',
'Biomedical engineers',
'Chemical engineers',
'Civil engineers',
'Computer hardware engineers',
'Electrical engineers',
'Electronics engineers, except computer',
'Environmental engineers',
'Health and safety engineers, except mining safety engineers and inspectors',
'Industrial engineers',
'Marine engineers and naval architects',
'Materials engineers',
'Mechanical engineers',
'Mining and geological engineers, including mining safety engineers',
'Nuclear engineers',
'Petroleum engineers',
'Engineers, all other',
'Architectural and civil drafters',
'Electrical and electronics drafters',
'Mechanical drafters',
'Drafters, all other',
'Aerospace engineering and operations technicians',
'Civil engineering technicians',
'Electrical and electronics engineering technicians',
'Electro-mechanical technicians',
'Environmental engineering technicians',
'Industrial engineering technicians',
'Mechanical engineering technicians',
'Engineering technicians, except drafters, all other',
'Surveying and mapping technicians',
'Animal scientists',
'Food scientists and technologists',
'Soil and plant scientists',
'Biochemists and biophysicists',
'Microbiologists',
'Zoologists and wildlife biologists',
'Biological scientists, all other',
'Conservation scientists',
'Foresters',
'Epidemiologists',
'Medical scientists, except epidemiologists',
'Life scientists, all other',
'Astronomers',
'Physicists',
'Atmospheric and space scientists',
'Chemists',
'Materials scientists',
'Environmental scientists and specialists, including health',
'Geoscientists, except hydrologists and geographers',
'Hydrologists',
'Physical scientists, all other',
'Economists',
'Survey researchers',
'Clinical, counseling, and school psychologists',
'Industrial-organizational psychologists',
'Psychologists, all other',
'Sociologists',
'Urban and regional planners',
'Anthropologists and archeologists',
'Geographers',
'Historians',
'Political scientists',
'Social scientists and related workers, all other',
'Agricultural and food science technicians',
'Biological technicians',
'Chemical technicians',
'Geological and petroleum technicians',
'Nuclear technicians',
'Social science research assistants',
'Environmental science and protection technicians, including health',
'Forensic science technicians',
'Forest and conservation technicians',
'Life, physical, and social science technicians, all other',
'Substance abuse and behavioral disorder counselors',
'Educational, guidance, school, and vocational counselors',
'Marriage and family therapists',
'Mental health counselors',
'Rehabilitation counselors',
'Counselors, all other',
'Child, family, and school social workers',
'Healthcare social workers',
'Mental health and substance abuse social workers',
'Social workers, all other',
'Health educators ',
'Probation officers and correctional treatment specialists',
'Social and human service assistants',
'Community health workers',
'Community and social service specialists, all other',
'Clergy',
'Directors, religious activities and education',
'Religious workers, all other',
'Lawyers',
'Judicial law clerks',
'Administrative law judges, adjudicators, and hearing officers',
'Arbitrators, mediators, and conciliators',
'Judges, magistrate judges, and magistrates',
'Paralegals and legal assistants',
'Court reporters',
'Title examiners, abstractors, and searchers',
'Legal support workers, all other',
'Business teachers, postsecondary',
'Computer science teachers, postsecondary',
'Mathematical science teachers, postsecondary',
'Architecture teachers, postsecondary',
'Engineering teachers, postsecondary',
'Agricultural sciences teachers, postsecondary',
'Biological science teachers, postsecondary',
'Forestry and conservation science teachers, postsecondary',
'Atmospheric, earth, marine, and space sciences teachers, postsecondary',
'Chemistry teachers, postsecondary',
'Environmental science teachers, postsecondary',
'Physics teachers, postsecondary',
'Anthropology and archeology teachers, postsecondary',
'Area, ethnic, and cultural studies teachers, postsecondary',
'Economics teachers, postsecondary',
'Geography teachers, postsecondary',
'Political science teachers, postsecondary',
'Psychology teachers, postsecondary',
'Sociology teachers, postsecondary',
'Social sciences teachers, postsecondary, all other',
'Health specialties teachers, postsecondary',
'Nursing instructors and teachers, postsecondary',
'Education teachers, postsecondary',
'Library science teachers, postsecondary',
'Criminal justice and law enforcement teachers, postsecondary',
'Law teachers, postsecondary',
'Social work teachers, postsecondary',
'Art, drama, and music teachers, postsecondary',
'Communications teachers, postsecondary',
'English language and literature teachers, postsecondary',
'Foreign language and literature teachers, postsecondary',
'History teachers, postsecondary',
'Philosophy and religion teachers, postsecondary',
'Graduate teaching assistants',
'Home economics teachers, postsecondary',
'Recreation and fitness studies teachers, postsecondary',
'Vocational education teachers, postsecondary',
'Postsecondary teachers, all other',
'Preschool teachers, except special education',
'Kindergarten teachers, except special education',
'Elementary school teachers, except special education',
'Middle school teachers, except special and career/technical education',
'Career/technical education teachers, middle school',
'Secondary school teachers, except special and career/technical education',
'Career/technical education teachers, secondary school',
'Special education teachers, preschool',
'Special education teachers, kindergarten and elementary school',
'Special education teachers, middle school',
'Special education teachers, secondary school',
'Special education teachers, all other',
'Adult basic and secondary education and literacy teachers and instructors ',
'Self-enrichment education teachers',
'Teachers and instructors, all other',
'Archivists',
'Curators',
'Museum technicians and conservators',
'Librarians',
'Library technicians',
'Audio-visual and multimedia collections specialists',
'Farm and home management advisors',
'Instructional coordinators',
'Teacher assistants',
'Education, training, and library workers, all other',
'Art directors',
'Craft artists',
'Fine artists, including painters, sculptors, and illustrators',
'Multimedia artists and animators',
'Artists and related workers, all other',
'Commercial and industrial designers',
'Fashion designers',
'Floral designers',
'Graphic designers',
'Interior designers',
'Merchandise displayers and window trimmers',
'Set and exhibit designers',
'Designers, all other',
'Producers and directors',
'Athletes and sports competitors',
'Coaches and scouts',
'Umpires, referees, and other sports officials',
'Choreographers',
'Music directors and composers',
'Radio and television announcers',
'Public address system and other announcers',
'Broadcast news analysts',
'Reporters and correspondents',
'Public relations specialists',
'Editors',
'Technical writers',
'Writers and authors',
'Interpreters and translators',
'Media and communication workers, all other',
'Audio and video equipment technicians',
'Broadcast technicians',
'Radio operators',
'Sound engineering technicians',
'Photographers',
'Camera operators, television, video, and motion picture',
'Film and video editors',
'Media and communication equipment workers, all other',
'Chiropractors',
'Dentists, general',
'Oral and maxillofacial surgeons',
'Orthodontists',
'Prosthodontists',
'Dentists, all other specialists',
'Dietitians and nutritionists',
'Optometrists',
'Pharmacists',
'Anesthesiologists',
'Family and general practitioners',
'Internists, general',
'Obstetricians and gynecologists',
'Pediatricians, general',
'Psychiatrists',
'Surgeons',
'Physicians and surgeons, all other',
'Physician assistants',
'Podiatrists',
'Occupational therapists',
'Physical therapists',
'Radiation therapists',
'Recreational therapists',
'Respiratory therapists',
'Speech-language pathologists',
'Exercise physiologists',
'Therapists, all other',
'Veterinarians',
'Registered nurses',
'Nurse anesthetists',
'Nurse midwives',
'Nurse practitioners',
'Audiologists',
'Health diagnosing and treating practitioners, all other',
'Medical and clinical laboratory technologists',
'Medical and clinical laboratory technicians',
'Dental hygienists',
'Cardiovascular technologists and technicians',
'Diagnostic medical sonographers',
'Nuclear medicine technologists',
'Radiologic technologists ',
'Magnetic resonance imaging technologists',
'Emergency medical technicians and paramedics',
'Dietetic technicians',
'Pharmacy technicians',
'Psychiatric technicians',
'Respiratory therapy technicians',
'Surgical technologists',
'Veterinary technologists and technicians',
'Ophthalmic medical technicians',
'Licensed practical and licensed vocational nurses',
'Medical records and health information technicians',
'Opticians, dispensing',
'Orthotists and prosthetists',
'Hearing aid specialists',
'Health technologists and technicians, all other',
'Occupational health and safety specialists',
'Occupational health and safety technicians',
'Athletic trainers',
'Genetic counselors',
'Healthcare practitioners and technical workers, all other',
'Home health aides',
'Psychiatric aides',
'Nursing assistants',
'Orderlies',
'Occupational therapy assistants',
'Occupational therapy aides',
'Physical therapist assistants',
'Physical therapist aides',
'Massage therapists',
'Dental assistants',
'Medical assistants',
'Medical equipment preparers',
'Medical transcriptionists',
'Pharmacy aides',
'Veterinary assistants and laboratory animal caretakers',
'Phlebotomists',
'Healthcare support workers, all other',
'First-line supervisors of correctional officers',
'First-line supervisors of police and detectives',
'First-line supervisors of fire fighting and prevention workers',
'First-line supervisors of protective service workers, all other',
'Firefighters',
'Fire inspectors and investigators',
'Forest fire inspectors and prevention specialists',
'Bailiffs',
'Correctional officers and jailers',
'Detectives and criminal investigators',
'Fish and game wardens',
'Parking enforcement workers',
'Police and sheriff\'s patrol officers',
'Transit and railroad police',
'Animal control workers',
'Private detectives and investigators',
'Gaming surveillance officers and gaming investigators',
'Security guards',
'Crossing guards',
'Lifeguards, ski patrol, and other recreational protective service workers',
'Transportation security screeners',
'Protective service workers, all other',
'Chefs and head cooks',
'First-line supervisors of food preparation and serving workers',
'Cooks, fast food',
'Cooks, institution and cafeteria',
'Cooks, private household',
'Cooks, restaurant',
'Cooks, short order',
'Cooks, all other',
'Food preparation workers',
'Bartenders',
'Combined food preparation and serving workers, including fast food',
'Counter attendants, cafeteria, food concession, and coffee shop',
'Waiters and waitresses',
'Food servers, nonrestaurant',
'Dining room and cafeteria attendants and bartender helpers',
'Dishwashers',
'Hosts and hostesses, restaurant, lounge, and coffee shop',
'Food preparation and serving related workers, all other',
'First-line supervisors of housekeeping and janitorial workers',
'First-line supervisors of landscaping, lawn service, and groundskeeping workers',
'Janitors and cleaners, except maids and housekeeping cleaners',
'Maids and housekeeping cleaners',
'Building cleaning workers, all other',
'Pest control workers',
'Landscaping and groundskeeping workers',
'Pesticide handlers, sprayers, and applicators, vegetation',
'Tree trimmers and pruners',
'Grounds maintenance workers, all other',
'Gaming supervisors',
'Slot supervisors',
'First-line supervisors of personal service workers',
'Animal trainers',
'Nonfarm animal caretakers',
'Gaming dealers',
'Gaming and sports book writers and runners',
'Gaming service workers, all other',
'Motion picture projectionists',
'Ushers, lobby attendants, and ticket takers',
'Amusement and recreation attendants',
'Costume attendants',
'Locker room, coatroom, and dressing room attendants',
'Entertainment attendants and related workers, all other',
'Embalmers',
'Funeral attendants',
'Morticians, undertakers, and funeral directors',
'Barbers',
'Hairdressers, hairstylists, and cosmetologists',
'Makeup artists, theatrical and performance',
'Manicurists and pedicurists',
'Shampooers',
'Skincare specialists',
'Baggage porters and bellhops',
'Concierges',
'Tour guides and escorts',
'Travel guides',
'Childcare workers',
'Personal care aides',
'Fitness trainers and aerobics instructors',
'Recreation workers',
'Residential advisors',
'Personal care and service workers, all other',
'First-line supervisors of retail sales workers',
'First-line supervisors of non-retail sales workers',
'Cashiers',
'Gaming change persons and booth cashiers',
'Counter and rental clerks',
'Parts salespersons',
'Retail salespersons',
'Advertising sales agents',
'Insurance sales agents',
'Securities, commodities, and financial services sales agents',
'Travel agents',
'Sales representatives, services, all other',
'Sales representatives, wholesale and manufacturing, technical and scientific products',
'Sales representatives, wholesale and manufacturing, except technical and scientific products',
'Demonstrators and product promoters',
'Models',
'Real estate brokers',
'Real estate sales agents',
'Sales engineers',
'Telemarketers',
'Door-to-door sales workers, news and street vendors, and related workers',
'Sales and related workers, all other',
'First-line supervisors of office and administrative support workers',
'Switchboard operators, including answering service',
'Telephone operators',
'Communications equipment operators, all other',
'Bill and account collectors',
'Billing and posting clerks',
'Bookkeeping, accounting, and auditing clerks',
'Gaming cage workers',
'Payroll and timekeeping clerks',
'Procurement clerks',
'Tellers',
'Financial clerks, all other',
'Brokerage clerks',
'Correspondence clerks',
'Court, municipal, and license clerks',
'Credit authorizers, checkers, and clerks',
'Customer service representatives',
'Eligibility interviewers, government programs',
'File clerks',
'Hotel, motel, and resort desk clerks',
'Interviewers, except eligibility and loan',
'Library assistants, clerical',
'Loan interviewers and clerks',
'New accounts clerks',
'Order clerks',
'Human resources assistants, except payroll and timekeeping',
'Receptionists and information clerks',
'Reservation and transportation ticket agents and travel clerks',
'Information and record clerks, all other',
'Cargo and freight agents',
'Couriers and messengers',
'Police, fire, and ambulance dispatchers',
'Dispatchers, except police, fire, and ambulance',
'Meter readers, utilities',
'Postal service clerks',
'Postal service mail carriers',
'Postal service mail sorters, processors, and processing machine operators',
'Production, planning, and expediting clerks',
'Shipping, receiving, and traffic clerks',
'Stock clerks and order fillers',
'Weighers, measurers, checkers, and samplers, recordkeeping',
'Executive secretaries and executive administrative assistants',
'Legal secretaries',
'Medical secretaries',
'Secretaries and administrative assistants, except legal, medical, and executive',
'Computer operators',
'Data entry keyers',
'Word processors and typists',
'Desktop publishers',
'Insurance claims and policy processing clerks',
'Mail clerks and mail machine operators, except postal service',
'Office clerks, general',
'Office machine operators, except computer',
'Proofreaders and copy markers',
'Statistical assistants',
'Office and administrative support workers, all other',
'First-line supervisors of farming, fishing, and forestry workers',
'Agricultural inspectors',
'Animal breeders',
'Graders and sorters, agricultural products',
'Agricultural equipment operators',
'Farmworkers and laborers, crop, nursery, and greenhouse',
'Farmworkers, farm, ranch, and aquacultural animals',
'Agricultural workers, all other',
'Fishers and related fishing workers',
'Forest and conservation workers',
'Fallers',
'Logging equipment operators',
'Log graders and scalers',
'Logging workers, all other',
'First-line supervisors of construction trades and extraction workers',
'Boilermakers',
'Brickmasons and blockmasons',
'Stonemasons',
'Carpenters',
'Carpet installers',
'Floor layers, except carpet, wood, and hard tiles',
'Floor sanders and finishers',
'Tile and marble setters',
'Cement masons and concrete finishers',
'Terrazzo workers and finishers',
'Construction laborers',
'Paving, surfacing, and tamping equipment operators',
'Pile-driver operators',
'Operating engineers and other construction equipment operators',
'Drywall and ceiling tile installers',
'Tapers',
'Electricians',
'Glaziers',
'Insulation workers, floor, ceiling, and wall',
'Insulation workers, mechanical',
'Painters, construction and maintenance',
'Paperhangers',
'Pipelayers',
'Plumbers, pipefitters, and steamfitters',
'Plasterers and stucco masons',
'Reinforcing iron and rebar workers',
'Roofers',
'Sheet metal workers',
'Structural iron and steel workers',
'Solar photovoltaic installers',
'Helpers--brickmasons, blockmasons, stonemasons, and tile and marble setters',
'Helpers--carpenters',
'Helpers--electricians',
'Helpers--painters, paperhangers, plasterers, and stucco masons',
'Helpers--pipelayers, plumbers, pipefitters, and steamfitters',
'Helpers--roofers',
'Helpers, construction trades, all other',
'Construction and building inspectors',
'Elevator installers and repairers',
'Fence erectors',
'Hazardous materials removal workers',
'Highway maintenance workers',
'Rail-track laying and maintenance equipment operators',
'Septic tank servicers and sewer pipe cleaners',
'Segmental pavers',
'Construction and related workers, all other',
'Derrick operators, oil and gas',
'Rotary drill operators, oil and gas',
'Service unit operators, oil, gas, and mining',
'Earth drillers, except oil and gas',
'Explosives workers, ordnance handling experts, and blasters',
'Continuous mining machine operators',
'Mine cutting and channeling machine operators',
'Mining machine operators, all other',
'Rock splitters, quarry',
'Roof bolters, mining',
'Roustabouts, oil and gas',
'Helpers--extraction workers',
'Extraction workers, all other',
'First-line supervisors of mechanics, installers, and repairers',
'Computer, automated teller, and office machine repairers',
'Radio, cellular, and tower equipment installers and repairs',
'Telecommunications equipment installers and repairers, except line installers',
'Avionics technicians',
'Electric motor, power tool, and related repairers',
'Electrical and electronics installers and repairers, transportation equipment',
'Electrical and electronics repairers, commercial and industrial equipment',
'Electrical and electronics repairers, powerhouse, substation, and relay',
'Electronic equipment installers and repairers, motor vehicles',
'Electronic home entertainment equipment installers and repairers',
'Security and fire alarm systems installers',
'Aircraft mechanics and service technicians',
'Automotive body and related repairers',
'Automotive glass installers and repairers',
'Automotive service technicians and mechanics',
'Bus and truck mechanics and diesel engine specialists',
'Farm equipment mechanics and service technicians',
'Mobile heavy equipment mechanics, except engines',
'Rail car repairers',
'Motorboat mechanics and service technicians',
'Motorcycle mechanics',
'Outdoor power equipment and other small engine mechanics',
'Bicycle repairers',
'Recreational vehicle service technicians',
'Tire repairers and changers',
'Mechanical door repairers',
'Control and valve installers and repairers, except mechanical door',
'Heating, air conditioning, and refrigeration mechanics and installers',
'Home appliance repairers',
'Industrial machinery mechanics',
'Maintenance workers, machinery',
'Millwrights',
'Refractory materials repairers, except brickmasons',
'Electrical power-line installers and repairers',
'Telecommunications line installers and repairers',
'Camera and photographic equipment repairers',
'Medical equipment repairers',
'Musical instrument repairers and tuners',
'Watch repairers',
'Precision instrument and equipment repairers, all other',
'Maintenance and repair workers, general',
'Wind turbine service technicians',
'Coin, vending, and amusement machine servicers and repairers',
'Commercial divers',
'Fabric menders, except garment',
'Locksmiths and safe repairers',
'Manufactured building and mobile home installers',
'Riggers',
'Signal and track switch repairers',
'Helpers--installation, maintenance, and repair workers',
'Installation, maintenance, and repair workers, all other',
'First-line supervisors of production and operating workers',
'Aircraft structure, surfaces, rigging, and systems assemblers',
'Coil winders, tapers, and finishers',
'Electrical and electronic equipment assemblers',
'Electromechanical equipment assemblers',
'Engine and other machine assemblers',
'Structural metal fabricators and fitters',
'Fiberglass laminators and fabricators',
'Team assemblers',
'Timing device assemblers and adjusters',
'Assemblers and fabricators, all other',
'Bakers',
'Butchers and meat cutters',
'Meat, poultry, and fish cutters and trimmers',
'Slaughterers and meat packers',
'Food and tobacco roasting, baking, and drying machine operators and tenders',
'Food batchmakers',
'Food cooking machine operators and tenders',
'Food processing workers, all other',
'Computer-controlled machine tool operators, metal and plastic',
'Computer numerically controlled machine tool programmers, metal and plastic',
'Extruding and drawing machine setters, operators, and tenders, metal and plastic',
'Forging machine setters, operators, and tenders, metal and plastic',
'Rolling machine setters, operators, and tenders, metal and plastic',
'Cutting, punching, and press machine setters, operators, and tenders, metal and plastic',
'Drilling and boring machine tool setters, operators, and tenders, metal and plastic',
'Grinding, lapping, polishing, and buffing machine tool setters, operators, and tenders, metal and plastic',
'Lathe and turning machine tool setters, operators, and tenders, metal and plastic',
'Milling and planing machine setters, operators, and tenders, metal and plastic',
'Machinists',
'Metal-refining furnace operators and tenders',
'Pourers and casters, metal',
'Model makers, metal and plastic',
'Patternmakers, metal and plastic',
'Foundry mold and coremakers',
'Molding, coremaking, and casting machine setters, operators, and tenders, metal and plastic',
'Multiple machine tool setters, operators, and tenders, metal and plastic',
'Tool and die makers',
'Welders, cutters, solderers, and brazers',
'Welding, soldering, and brazing machine setters, operators, and tenders',
'Heat treating equipment setters, operators, and tenders, metal and plastic',
'Layout workers, metal and plastic',
'Plating and coating machine setters, operators, and tenders, metal and plastic',
'Tool grinders, filers, and sharpeners',
'Metal workers and plastic workers, all other',
'Prepress technicians and workers',
'Printing press operators',
'Print binding and finishing workers',
'Laundry and dry-cleaning workers',
'Pressers, textile, garment, and related materials',
'Sewing machine operators',
'Shoe and leather workers and repairers',
'Shoe machine operators and tenders',
'Sewers, hand',
'Tailors, dressmakers, and custom sewers',
'Textile bleaching and dyeing machine operators and tenders',
'Textile cutting machine setters, operators, and tenders',
'Textile knitting and weaving machine setters, operators, and tenders',
'Textile winding, twisting, and drawing out machine setters, operators, and tenders',
'Extruding and forming machine setters, operators, and tenders, synthetic and glass fibers',
'Fabric and apparel patternmakers',
'Upholsterers',
'Textile, apparel, and furnishings workers, all other',
'Cabinetmakers and bench carpenters',
'Furniture finishers',
'Model makers, wood',
'Patternmakers, wood',
'Sawing machine setters, operators, and tenders, wood',
'Woodworking machine setters, operators, and tenders, except sawing',
'Woodworkers, all other',
'Nuclear power reactor operators',
'Power distributors and dispatchers',
'Power plant operators',
'Stationary engineers and boiler operators',
'Water and wastewater treatment plant and system operators',
'Chemical plant and system operators',
'Gas plant operators',
'Petroleum pump system operators, refinery operators, and gaugers',
'Plant and system operators, all other',
'Chemical equipment operators and tenders',
'Separating, filtering, clarifying, precipitating, and still machine setters, operators, and tenders',
'Crushing, grinding, and polishing machine setters, operators, and tenders',
'Grinding and polishing workers, hand',
'Mixing and blending machine setters, operators, and tenders',
'Cutters and trimmers, hand',
'Cutting and slicing machine setters, operators, and tenders',
'Extruding, forming, pressing, and compacting machine setters, operators, and tenders',
'Furnace, kiln, oven, drier, and kettle operators and tenders',
'Inspectors, testers, sorters, samplers, and weighers',
'Jewelers and precious stone and metal workers',
'Dental laboratory technicians',
'Medical appliance technicians',
'Ophthalmic laboratory technicians',
'Packaging and filling machine operators and tenders',
'Coating, painting, and spraying machine setters, operators, and tenders',
'Painters, transportation equipment',
'Painting, coating, and decorating workers',
'Semiconductor processors',
'Photographic process workers and processing machine operators',
'Adhesive bonding machine operators and tenders',
'Cleaning, washing, and metal pickling equipment operators and tenders',
'Cooling and freezing equipment operators and tenders',
'Etchers and engravers',
'Molders, shapers, and casters, except metal and plastic',
'Paper goods machine setters, operators, and tenders',
'Tire builders',
'Helpers--production workers',
'Production workers, all other',
'Aircraft cargo handling supervisors',
'First-line supervisors of helpers, laborers, and material movers, hand',
'First-line supervisors of transportation and material-moving machine and vehicle operators',
'Airline pilots, copilots, and flight engineers',
'Commercial pilots',
'Air traffic controllers',
'Airfield operations specialists',
'Flight attendants',
'Ambulance drivers and attendants, except emergency medical technicians',
'Bus drivers, transit and intercity ',
'Bus drivers, school or special client ',
'Driver/sales workers',
'Heavy and tractor-trailer truck drivers',
'Light truck or delivery services drivers',
'Taxi drivers and chauffeurs',
'Motor vehicle operators, all other',
'Locomotive engineers',
'Locomotive firers',
'Rail yard engineers, dinkey operators, and hostlers',
'Railroad brake, signal, and switch operators',
'Railroad conductors and yardmasters',
'Subway and streetcar operators',
'Rail transportation workers, all other',
'Sailors and marine oilers',
'Captains, mates, and pilots of water vessels',
'Motorboat operators',
'Ship engineers',
'Bridge and lock tenders',
'Parking lot attendants',
'Automotive and watercraft service attendants',
'Traffic technicians',
'Transportation inspectors',
'Transportation attendants, except flight attendants ',
'Transportation workers, all other',
'Conveyor operators and tenders',
'Crane and tower operators',
'Dredge operators',
'Excavating and loading machine and dragline operators',
'Loading machine operators, underground mining',
'Hoist and winch operators',
'Industrial truck and tractor operators',
'Cleaners of vehicles and equipment',
'Laborers and freight, stock, and material movers, hand',
'Machine feeders and offbearers',
'Packers and packagers, hand',
'Gas compressor and gas pumping station operators',
'Pump operators, except wellhead pumpers',
'Wellhead pumpers',
'Refuse and recyclable material collectors',
'Mine shuttle car operators',
'Tank car, truck, and ship loaders',
'Material moving workers, all other'
];